# Generated by Django 3.0.6 on 2020-05-21 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjustment',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='class',
            name='found_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='birth',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='enroll_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='enroll_date',
            field=models.DateTimeField(),
        ),
    ]
