# Generated by Django 3.0.6 on 2020-05-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200521_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selection',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='selection',
            unique_together={('lecture', 'student')},
        ),
    ]
