# Generated by Django 3.0.6 on 2020-05-22 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200521_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downgrade',
            name='adjustment',
        ),
        migrations.RemoveField(
            model_name='downgrade',
            name='student',
        ),
        migrations.AddField(
            model_name='adjustment',
            name='extra',
            field=models.IntegerField(choices=[(0, 'yes or suspend'), (1, 'no or support_teching'), (2, 'none')], default=0),
        ),
        migrations.AlterField(
            model_name='adjustment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='adjustment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Student'),
        ),
        migrations.AlterField(
            model_name='major',
            name='charge_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.Person'),
        ),
        migrations.AlterField(
            model_name='selection',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Person'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Person'),
        ),
        migrations.AlterUniqueTogether(
            name='adjustment',
            unique_together={('student', 'type')},
        ),
        migrations.DeleteModel(
            name='ChangeMajor',
        ),
        migrations.DeleteModel(
            name='Downgrade',
        ),
    ]
